repositories: []

releases:
  - name: hutbot
    namespace: default
    chart: ./charts/hutbot
    values:
      - image:
          repository: ghcr.io/mittwald/hutbot
          tag: "latest"
        replicaCount: 1
      - slack:
          appToken: "{{ env \"SLACK_APP_TOKEN\" }}"
          botToken: "{{ env \"SLACK_BOT_TOKEN\" }}"
      - opsgenie:
          token: "{{ env \"OPSGENIE_TOKEN\" }}"
          heartbeatName: "{{ env \"OPSGENIE_HEARTBEAT_NAME\" }}"
      - employeeList:
          username: "{{ env \"EMPLOYEE_LIST_USERNAME\" }}"
          password: "{{ env \"EMPLOYEE_LIST_PASSWORD\" }}"
          mappings: "{{ env \"EMPLOYEE_LIST_MAPPINGS\" }}"