# Default values for hutbot chart

replicaCount: 1

image:
  repository: hutbot
  tag: "latest"
  pullPolicy: Always

slack:
  appToken: ""
  botToken: ""

opsgenie:
  token: ""
  heartbeatName: ""

employeeList:
  username: ""
  password: ""
  mappings: ""

resources: {}
