# Default values for hutbot chart

replicaCount: 1

image:
  repository: hutbot
  tag: "latest"
  pullPolicy: Always

slack:
  appToken: ""
  botToken: ""

opsgenie:
  token: ""
  heartbeatName: ""

employeeList:
  username: ""
  password: ""
  mappings: ""

resources: {}

# Persistence configuration for storing the bot config file on a PersistentVolumeClaim
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 100Mi
  storageClass: ""
  mountPath: "/data"
