apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  SLACK_APP_TOKEN: {{ .Values.slack.appToken | quote }}
  SLACK_BOT_TOKEN: {{ .Values.slack.botToken | quote }}
  OPSGENIE_TOKEN: {{ .Values.opsgenie.token | quote }}
  OPSGENIE_HEARTBEAT_NAME: {{ .Values.opsgenie.heartbeatName | quote }}

  EMPLOYEE_LIST_USERNAME: {{ .Values.employeeList.username | quote }}
  EMPLOYEE_LIST_PASSWORD: {{ .Values.employeeList.password | quote }}
  EMPLOYEE_LIST_MAPPINGS: {{ .Values.employeeList.mappings | quote }}